# Generated by Django 6.0.3 on 2026-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
    ]
