# Generated by Django 6.0.3 on 2026-03-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_product_is_preorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='farmer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farmers/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
