# Generated by Django 6.0.3 on 2026-03-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_remove_farmer_image_url_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='farmer',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='farmers/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
