# Generated by Django 6.0.3 on 2026-03-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_address_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
