# Generated by Django 6.0.3 on 2026-03-31 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_orderitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='house_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
