# Generated by Django 6.0.3 on 2026-04-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_address_area_address_house_no_address_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
