# Generated by Django 6.0.3 on 2026-04-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_farmer_farm_name_alter_farmer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
