# Generated by Django 6.0.3 on 2026-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_farmer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('farmer', 'Farmer')], default='customer', max_length=10),
        ),
    ]
